### PR TITLE
fix for lime stuffs

### PR DESCRIPTION
**Pull request by Vortex2Oblivion**

### CODE REVIEW

**Review by SanicBTW — APPROVED** [review]
Looks fine, I'll be testing these changes in a moment and merge the changes to master.

**Comment by SanicBTW** [comment]
Ok so its working perfectly fine tho I would only copy the necessary DLL's into the projects directory to avoid copying unnecessary files (.dll.lib), anyways I'm going to merge this pull request and push an example for HaxeFlixel 
image

**Comment by Vortex2Oblivion** [comment]
> I would only copy the necessary DLL's into the projects directory to avoid copying unnecessary files (.dll.lib)

A I forgot there was a .lib file in there lmao

**Comment by SanicBTW** [comment]
> > I would only copy the necessary DLL's into the projects directory to avoid copying unnecessary files (.dll.lib)
> 
> A I forgot there was a .lib file in there lmao
> 

LMAOOO it's okay tho I added the exclusion to the xml in the latest commit

**Pull request merged**
